# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Cypress Report
on:
  push:
    branches:  
      - 'master'
jobs:
  cypress-test:
    name: 'cypress Test'
    runs-on: windows-latest
    env:
      BASE_URL: http://10.1.146.29:8080/#/
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: 'install '
        run:  npm install
      - name: Run Cypress tests
        run: npx cypress run
        continue-on-error: false
      
